import type { Exercise } from "./db"

export const exercisesData: Exercise[] = [
  // MONTH 1: Healing & Mobility (Weeks 1-4)
  {
    id: "cat-cow",
    nameEn: "Cat-Cow Stretch",
    nameNe: "बिरालो-गाई",
    descriptionEn:
      "On hands and knees, alternate between arching and rounding your spine. Breathe deeply with each movement.",
    descriptionNe: "हात र घुँडामा, आफ्नो मेरुदण्डलाई वैकल्पिक रूपमा घुमाउनुहोस्। प्रत्येक आन्दोलनसँग गहिरो सास फेर्नुहोस्।",
    reps: "10 reps",
    duration: "2-3 minutes",
    week: 1,
    category: "mobility",
    svgPath: "cat-cow",
    videoUrl: "https://www.youtube.com/embed/Fa4ZMS5M7xA",
  },
  {
    id: "pelvic-tilt",
    nameEn: "Pelvic Tilt",
    nameNe: "पेल्भिक टिल्ट",
    descriptionEn: "Lie on back, knees bent. Flatten lower back against floor by tilting pelvis. Strengthens core.",
    descriptionNe: "पीठमा सुत्नुहोस्, घुँडा झुकाउनुहोस्। श्रोणि झुकाएर तल्लो ढाडलाई भुइँमा समतल गर्नुहोस्।",
    reps: "2 sets × 10 reps",
    duration: "2-3 minutes",
    week: 1,
    category: "core",
    svgPath: "pelvic-tilt",
    videoUrl: "https://www.youtube.com/embed/z73XjJDSXaE",
  },
  {
    id: "knee-to-chest",
    nameEn: "Knee-to-Chest Stretch",
    nameNe: "घुँडा छातीमा",
    descriptionEn: "Lie on back, bring one knee to chest. Hold for 10 seconds. Stretches lower back gently.",
    descriptionNe: "पीठमा सुत्नुहोस्, एक घुँडा छातीमा ल्याउनुहोस्। १० सेकेन्ड होल्ड गर्नुहोस्।",
    reps: "10 sec × 2 each leg",
    duration: "2 minutes",
    week: 1,
    category: "mobility",
    svgPath: "knee-to-chest",
    videoUrl: "https://www.youtube.com/embed/1UVIT5G1R2k",
  },
  {
    id: "cobra-pose",
    nameEn: "Cobra Pose",
    nameNe: "कोब्रा आसन",
    descriptionEn: "Lie face down, push upper body up with arms. Keep hips on ground. Extends spine gently.",
    descriptionNe: "अनुहार तल राखेर सुत्नुहोस्, हातले माथिल्लो शरीर माथि धकेल्नुहोस्। कम्मर भुइँमा राख्नुहोस्।",
    reps: "5-10 sec × 3",
    duration: "2-3 minutes",
    week: 1,
    category: "mobility",
    svgPath: "cobra-pose",
    videoUrl: "https://www.youtube.com/embed/L9HZ9U_ZXLc",
  },
  {
    id: "childs-pose",
    nameEn: "Child's Pose",
    nameNe: "बालासन",
    descriptionEn: "Kneel and sit back on heels, stretch arms forward. Relaxes spine and shoulders.",
    descriptionNe: "घुँडा टेकेर एड़ीमा बस्नुहोस्, हात अगाडि फैलाउनुहोस्। मेरुदण्ड र काँध आराम गर्छ।",
    reps: "20 sec × 2",
    duration: "1-2 minutes",
    week: 1,
    category: "mobility",
    svgPath: "childs-pose",
    videoUrl: "https://www.youtube.com/embed/hWHf-Kia-ZE",
  },
  {
    id: "chin-tucks",
    nameEn: "Chin Tuck",
    nameNe: "चिन टक",
    descriptionEn: "Gently pull your chin back, creating a double chin. Hold for 5 seconds. Strengthens neck muscles.",
    descriptionNe: "बिस्तारै आफ्नो चिनलाई पछाडि तान्नुहोस्। ५ सेकेन्ड होल्ड गर्नुहोस्। घाँटीको मांसपेशी बलियो बनाउँछ।",
    reps: "10 reps × 2",
    duration: "2 minutes",
    week: 1,
    category: "neck",
    svgPath: "chin-tucks",
    videoUrl: "https://www.youtube.com/embed/vhFGQxDVzF8",
  },

  // MONTH 2: Strength & Posture Correction (Weeks 5-8)
  {
    id: "glute-bridge",
    nameEn: "Glute Bridge",
    nameNe: "ग्लुट ब्रिज",
    descriptionEn: "Lie on back, knees bent. Lift hips up, squeeze glutes. Hold for 3 seconds. Strengthens lower back.",
    descriptionNe: "पीठमा सुत्नुहोस्, घुँडा झुकाउनुहोस्। कम्मर माथि उठाउनुहोस्। ३ सेकेन्ड होल्ड गर्नुहोस्।",
    reps: "15 reps × 3",
    duration: "3-4 minutes",
    week: 5,
    category: "strength",
    svgPath: "glute-bridge",
    videoUrl: "https://www.youtube.com/embed/WtilA9IJX1c",
  },
  {
    id: "bird-dog",
    nameEn: "Bird-Dog",
    nameNe: "बर्ड-डग व्यायाम",
    descriptionEn: "On hands and knees, extend opposite arm and leg. Hold for 5-10 seconds. Builds core stability.",
    descriptionNe: "हात र घुँडामा, विपरीत हात र खुट्टा फैलाउनुहोस्। ५-१० सेकेन्ड होल्ड गर्नुहोस्।",
    reps: "10 reps × 3",
    duration: "3-4 minutes",
    week: 5,
    category: "core",
    svgPath: "bird-dog",
    videoUrl: "https://www.youtube.com/embed/aFk1SjShgO4",
  },
  {
    id: "wall-plank",
    nameEn: "Wall Plank",
    nameNe: "भित्तामा प्लान्क",
    descriptionEn: "Stand facing wall, lean on forearms. Hold body straight. Beginner-friendly core exercise.",
    descriptionNe: "भित्ता तिर उभिनुहोस्, कुहिनोमा झुक्नुहोस्। शरीर सीधा राख्नुहोस्।",
    reps: "15 sec × 3",
    duration: "2 minutes",
    week: 5,
    category: "core",
    svgPath: "wall-plank",
    videoUrl: "https://www.youtube.com/embed/2FetGxRE3SY",
  },
  {
    id: "shoulder-blade-squeeze",
    nameEn: "Shoulder Blade Squeeze",
    nameNe: "काँध ब्लेड निचोड",
    descriptionEn: "Sit or stand, squeeze shoulder blades together. Hold for 5 seconds. Improves posture.",
    descriptionNe: "बस्नुहोस् वा उभिनुहोस्, काँधको ब्लेड सँगै निचोड्नुहोस्। ५ सेकेन्ड होल्ड गर्नुहोस्।",
    reps: "10 reps × 2",
    duration: "2 minutes",
    week: 5,
    category: "posture",
    svgPath: "shoulder-blade-squeeze",
    videoUrl: "https://www.youtube.com/embed/p_lFyLMCZZw",
  },
  {
    id: "neck-resistance",
    nameEn: "Neck Resistance Press",
    nameNe: "घाँटी प्रतिरोध",
    descriptionEn: "Place hand on forehead, press head forward against hand. Hold for 5 seconds. Strengthens neck.",
    descriptionNe: "निधारमा हात राख्नुहोस्, हातको विरुद्धमा टाउको अगाडि थिच्नुहोस्। ५ सेकेन्ड होल्ड गर्नुहोस्।",
    reps: "5 sec × 5",
    duration: "2 minutes",
    week: 5,
    category: "neck",
    svgPath: "neck-resistance",
    videoUrl: "https://www.youtube.com/embed/VWztt_QlnGo",
  },

  // MONTH 3: Stability & Gym Preparation (Weeks 9-12)
  {
    id: "plank",
    nameEn: "Plank",
    nameNe: "प्लान्क व्यायाम",
    descriptionEn: "Hold push-up position on forearms. Keep body straight. Builds core endurance.",
    descriptionNe: "कुहिनोमा पुश-अप स्थिति होल्ड गर्नुहोस्। शरीर सीधा राख्नुहोस्।",
    reps: "20 sec × 3",
    duration: "2-3 minutes",
    week: 9,
    category: "core",
    svgPath: "plank",
    videoUrl: "https://www.youtube.com/embed/jGKZaQTZi74",
  },
  {
    id: "glute-bridge-march",
    nameEn: "Glute Bridge March",
    nameNe: "ग्लुट ब्रिज मार्च",
    descriptionEn: "Hold glute bridge position, lift one foot off ground alternately. Challenges stability.",
    descriptionNe: "ग्लुट ब्रिज स्थिति होल्ड गर्नुहोस्, एक खुट्टा वैकल्पिक रूपमा माथि उठाउनुहोस्।",
    reps: "10 reps × 3",
    duration: "3 minutes",
    week: 9,
    category: "strength",
    svgPath: "glute-bridge-march",
    videoUrl: "https://www.youtube.com/embed/YQmpO9VT2X4",
  },
  {
    id: "bird-dog-hold",
    nameEn: "Bird-Dog Hold",
    nameNe: "बर्ड-डग होल्ड",
    descriptionEn: "Extend opposite arm and leg, hold position for 3 seconds. Advanced core stability.",
    descriptionNe: "विपरीत हात र खुट्टा फैलाउनुहोस्, ३ सेकेन्ड स्थिति होल्ड गर्नुहोस्।",
    reps: "3 sec × 10",
    duration: "3 minutes",
    week: 9,
    category: "core",
    svgPath: "bird-dog-hold",
    videoUrl: "https://www.youtube.com/embed/aFk1SjShgO4",
  },
  {
    id: "cobra-extension",
    nameEn: "Cobra Extension",
    nameNe: "कोब्रा विस्तार",
    descriptionEn: "Lie face down, push up with arms fully extended. Hold briefly. Strengthens back extensors.",
    descriptionNe: "अनुहार तल राखेर सुत्नुहोस्, हात पूर्ण रूपमा फैलाएर माथि धकेल्नुहोस्।",
    reps: "10 reps × 2",
    duration: "2-3 minutes",
    week: 9,
    category: "strength",
    svgPath: "cobra-extension",
    videoUrl: "https://www.youtube.com/embed/L9HZ9U_ZXLc",
  },
  {
    id: "side-plank",
    nameEn: "Side Plank",
    nameNe: "साइड प्लान्क",
    descriptionEn: "Lie on side, prop up on forearm. Lift hips off ground. Strengthens obliques and spine stabilizers.",
    descriptionNe: "छेउमा सुत्नुहोस्, कुहिनोमा सहारा लिनुहोस्। कम्मर माथि उठाउनुहोस्।",
    reps: "15 sec each × 2",
    duration: "2 minutes",
    week: 9,
    category: "core",
    svgPath: "side-plank",
    videoUrl: "https://www.youtube.com/embed/zS0qj9DCVEw",
  },
]

export const dosAndDonts = {
  dos: {
    en: ["Walk daily 20-30 mins", "Use thin pillow, firm bed", "Keep straight posture", "Stay hydrated"],
    ne: ["दैनिक २०-३० मिनेट हिँड्नुहोस्", "पातलो तकिया, बलियो ओछ्यान प्रयोग गर्नुहोस्", "सीधा मुद्रा राख्नुहोस्", "हाइड्रेटेड रहनुहोस्"],
  },
  donts: {
    en: ["Sit >45 mins continuously", "Use multiple pillows", "Bend or twist suddenly", "Lift heavy weights"],
    ne: ["४५ मिनेट भन्दा बढी लगातार नबस्नुहोस्", "धेरै तकिया प्रयोग नगर्नुहोस्", "अचानक झुक्नु वा घुमाउनु हुँदैन", "भारी तौल नउठाउनुहोस्"],
  },
}

export const motivationalQuote = {
  en: "Slow progress is still progress. Your spine heals with patience, not pressure.",
  ne: "ढिलो प्रगति पनि प्रगति हो। तपाईंको मेरुदण्ड धैर्यले निको हुन्छ, दबाबले होइन।",
}
